# Generated by Django 5.2.1 on 2025-05-10 11:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_ingreso', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('CLUB', 'Club'), ('SELECCION', 'Selección')], default='CLUB', max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='inventario.country')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_coste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('start_year', 'end_year')},
            },
        ),
        migrations.CreateModel(
            name='ModeloCamiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('FAN', 'Fan'), ('PLAYER', 'Player'), ('RETRO', 'Retro'), ('INFANTIL', 'Infantil'), ('KIT', 'Kit')], max_length=10)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='inventario.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='VarianteCamiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('XXXXL', 'XXXXXL'), ('XXXXXL', 'XXXXXXL'), ('2A', '2 años'), ('3A', '3 años'), ('4A', '4 años'), ('5A', '5 años'), ('6A', '6 años'), ('7A', '7 años'), ('8A', '8 años'), ('9A', '9 años'), ('10A', '10 años'), ('11A', '11 años'), ('12A', '12 años'), ('13A', '13 años'), ('14A', '14 años')], max_length=6)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.modelocamiseta')),
            ],
            options={
                'unique_together': {('modelo', 'talla')},
            },
        ),
        migrations.CreateModel(
            name='StockMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_mov', models.DateTimeField(default=django.utils.timezone.now)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.variantecamiseta')),
            ],
        ),
        migrations.CreateModel(
            name='CompraLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('coste_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.compra')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.variantecamiseta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.variantecamiseta')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.venta')),
            ],
        ),
    ]
