# Generated by Django 5.2.1 on 2025-05-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelocamiseta',
            name='tipo_kit',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('VISITANTE', 'Visitante'), ('TERCERA', 'Tercera equipación'), ('ALTERNATIVA', 'Alternativa')], default='LOCAL', help_text='Local/Visitante/Tercera/Alternativa', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='modelocamiseta',
            unique_together={('equipo', 'version', 'temporada', 'tipo_kit')},
        ),
    ]
